language: ruby
sudo: false
cache: bundler

# whitelist
branches:
  only:
    - gh-pages

rvm: 2.3.0
script: bundle exec jekyll build && bundle exec htmlproof -t --check-html --disable-external ./_site
install: bundle install

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
